version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: sports_tickets_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sports_tickets
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sports_tickets_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      otel-collector:
        condition: service_started
    volumes:
      - ./:/app
    working_dir: /app

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - ./docker/otel-collector/otel-collector.yml:/etc/otel-collector.yml
    ports:
      - "4317:4317"
      - "55679:55679"
      - "13133:13133"
      - "1777:1777"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268:14268"
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./docker/loki/loki-config.yml:/etc/loki/local-config.yml
      - loki-data:/tmp/loki
volumes:
  postgres_data:
  loki-data:
    driver: local
